### ISSUE TITLE
Need to automatically copy `.env.example` to `.env` when cloning templates

### ISSUE THREAD

**Issue by jacobsfletch** [payloadcms/create-payload-app#21]

**Comment by denolfe** [comment]
This should be handled by [src/lib/write-env-file.ts](https://github.com/payloadcms/create-payload-app/blob/master/src/lib/write-env-file.ts#L7). Likely need to evaluate the current functionality.

**Comment by denolfe** [comment]
Closed by 6f2dcfd44ee36d39706b10b1a7c4dd3a0e6e062f
